import json
import os
from datetime import datetime
from app.core.config import REPORTS_DIR


async def generate_vulnerability_report(
    title: str,
    target: str,
    findings: list[dict],
    recommendations: list[str] | None = None,
    user_name: str = "RudraX User",
) -> dict:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"vuln_report_{timestamp}.html"
    filepath = os.path.join(REPORTS_DIR, filename)

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info").lower()
        if sev in severity_counts:
            severity_counts[sev] += 1

    severity_colors = {
        "critical": "#dc2626", "high": "#ea580c",
        "medium": "#d97706", "low": "#2563eb", "info": "#6b7280",
    }

    findings_html = ""
    for i, f in enumerate(findings, 1):
        sev = f.get("severity", "info").lower()
        color = severity_colors.get(sev, "#6b7280")
        findings_html += f"""
        <div style="border-left: 4px solid {color}; padding: 12px; margin: 10px 0; background: #1a1a2e;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <strong style="color: #e0e0e0;">#{i} {f.get('vulnerability', f.get('finding', 'Finding'))}</strong>
                <span style="background: {color}; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px;">{sev.upper()}</span>
            </div>
            <p style="color: #a0a0a0; margin: 8px 0;">{f.get('detail', f.get('description', 'No details'))}</p>
        </div>"""

    recs_html = ""
    if recommendations:
        for r in recommendations:
            recs_html += f'<li style="color: #a0a0a0; margin: 4px 0;">{r}</li>'
    else:
        recs_html = '<li style="color: #a0a0a0;">Run a full scan to generate specific recommendations</li>'

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>RudraX Vulnerability Report - {title}</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #0a0a1a; color: #e0e0e0; margin: 0; padding: 20px; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #0f172a, #1e293b); padding: 30px; border-radius: 12px; margin-bottom: 20px; border: 1px solid #334155; }}
        .header h1 {{ color: #06b6d4; margin: 0 0 10px 0; }}
        .header p {{ color: #94a3b8; margin: 4px 0; }}
        .summary {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; margin: 20px 0; }}
        .summary-card {{ text-align: center; padding: 15px; border-radius: 8px; border: 1px solid #334155; }}
        .summary-card .count {{ font-size: 28px; font-weight: bold; }}
        .summary-card .label {{ font-size: 12px; color: #94a3b8; }}
        .section {{ background: #0f172a; padding: 20px; border-radius: 12px; margin: 15px 0; border: 1px solid #334155; }}
        .section h2 {{ color: #06b6d4; border-bottom: 1px solid #334155; padding-bottom: 10px; }}
        .footer {{ text-align: center; color: #475569; margin-top: 30px; padding: 20px; }}
        @media print {{ body {{ background: white; color: black; }} }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>RudraX CyberSec - Vulnerability Report</h1>
            <p><strong>Title:</strong> {title}</p>
            <p><strong>Target:</strong> {target}</p>
            <p><strong>Date:</strong> {datetime.now().strftime("%B %d, %Y %H:%M")}</p>
            <p><strong>Generated by:</strong> {user_name}</p>
        </div>

        <div class="summary">
            <div class="summary-card" style="background: rgba(220,38,38,0.1);">
                <div class="count" style="color: #dc2626;">{severity_counts['critical']}</div>
                <div class="label">Critical</div>
            </div>
            <div class="summary-card" style="background: rgba(234,88,12,0.1);">
                <div class="count" style="color: #ea580c;">{severity_counts['high']}</div>
                <div class="label">High</div>
            </div>
            <div class="summary-card" style="background: rgba(217,119,6,0.1);">
                <div class="count" style="color: #d97706;">{severity_counts['medium']}</div>
                <div class="label">Medium</div>
            </div>
            <div class="summary-card" style="background: rgba(37,99,235,0.1);">
                <div class="count" style="color: #2563eb;">{severity_counts['low']}</div>
                <div class="label">Low</div>
            </div>
            <div class="summary-card" style="background: rgba(107,114,128,0.1);">
                <div class="count" style="color: #6b7280;">{severity_counts['info']}</div>
                <div class="label">Info</div>
            </div>
        </div>

        <div class="section">
            <h2>Findings ({len(findings)})</h2>
            {findings_html}
        </div>

        <div class="section">
            <h2>Recommendations</h2>
            <ul>{recs_html}</ul>
        </div>

        <div class="footer">
            <p>Generated by RudraX CyberSec Platform v2.0 | A Lalit Pandit Product</p>
            <p>CONFIDENTIAL - For authorized use only</p>
        </div>
    </div>
</body>
</html>"""

    with open(filepath, "w") as f:
        f.write(html)

    return {
        "report_path": filepath,
        "filename": filename,
        "title": title,
        "target": target,
        "total_findings": len(findings),
        "severity_summary": severity_counts,
        "generated_at": datetime.now().isoformat(),
    }


async def generate_osint_report(target: str, osint_data: dict, user_name: str = "RudraX User") -> dict:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"osint_report_{timestamp}.html"
    filepath = os.path.join(REPORTS_DIR, filename)

    sections_html = ""
    for key, value in osint_data.items():
        if key == "ai_analysis":
            sections_html += f"""
            <div class="section">
                <h2>AI Analysis</h2>
                <pre style="white-space: pre-wrap; color: #a0a0a0;">{value}</pre>
            </div>"""
        else:
            sections_html += f"""
            <div class="section">
                <h2>{key.replace('_', ' ').title()}</h2>
                <pre style="white-space: pre-wrap; color: #a0a0a0;">{json.dumps(value, indent=2, default=str)[:3000]}</pre>
            </div>"""

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>RudraX OSINT Report - {target}</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #0a0a1a; color: #e0e0e0; margin: 0; padding: 20px; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #0f172a, #1e293b); padding: 30px; border-radius: 12px; margin-bottom: 20px; border: 1px solid #334155; }}
        .header h1 {{ color: #06b6d4; margin: 0 0 10px 0; }}
        .header p {{ color: #94a3b8; margin: 4px 0; }}
        .section {{ background: #0f172a; padding: 20px; border-radius: 12px; margin: 15px 0; border: 1px solid #334155; }}
        .section h2 {{ color: #06b6d4; border-bottom: 1px solid #334155; padding-bottom: 10px; }}
        .footer {{ text-align: center; color: #475569; margin-top: 30px; padding: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>RudraX CyberSec - OSINT Intelligence Report</h1>
            <p><strong>Target:</strong> {target}</p>
            <p><strong>Date:</strong> {datetime.now().strftime("%B %d, %Y %H:%M")}</p>
            <p><strong>Generated by:</strong> {user_name}</p>
        </div>
        {sections_html}
        <div class="footer">
            <p>Generated by RudraX CyberSec Platform v2.0 | A Lalit Pandit Product</p>
            <p>CONFIDENTIAL - For authorized use only</p>
        </div>
    </div>
</body>
</html>"""

    with open(filepath, "w") as f:
        f.write(html)

    return {
        "report_path": filepath,
        "filename": filename,
        "target": target,
        "generated_at": datetime.now().isoformat(),
    }
